/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#001714',
        'on-background': '#cde8e2',
        surface: '#001714',
        'surface-dim': '#001714',
        'surface-bright': '#263e39',
        'surface-container-lowest': '#00110e',
        'surface-container-low': '#071f1c',
        'surface-container': '#0b2420',
        'surface-container-high': '#162e2a',
        'surface-container-highest': '#213935',
        'surface-variant': '#213935',
        'on-surface': '#cde8e2',
        'on-surface-variant': '#c2c8c5',
        'inverse-surface': '#cde8e2',
        'inverse-on-surface': '#1d3530',
        outline: '#8c9290',
        'outline-variant': '#424846',
        'surface-tint': '#b4cbc6',
        primary: '#b4cbc6',
        'on-primary': '#203431',
        'primary-container': '#0a1f1c',
        'on-primary-container': '#728884',
        'inverse-primary': '#4d635f',
        secondary: '#c9c6c0',
        'on-secondary': '#31312c',
        'secondary-container': '#474742',
        'on-secondary-container': '#b7b5af',
        tertiary: '#e8c08e',
        'on-tertiary': '#432c06',
        'tertiary-container': '#2a1800',
        'on-tertiary-container': '#a07e52',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#d0e7e2',
        'primary-fixed-dim': '#b4cbc6',
        'on-primary-fixed': '#0a1f1c',
        'on-primary-fixed-variant': '#364b47',
        'secondary-fixed': '#e5e2db',
        'secondary-fixed-dim': '#c9c6c0',
        'on-secondary-fixed': '#1c1c18',
        'on-secondary-fixed-variant': '#474742',
        'tertiary-fixed': '#ffddb5',
        'tertiary-fixed-dim': '#e8c08e',
        'on-tertiary-fixed': '#2a1800',
        'on-tertiary-fixed-variant': '#5d421b',
      },
      fontFamily: {
        sans: ['Hanken Grotesk', 'sans-serif'],
        serif: ['Playfair Display', 'serif'],
        display: ['Playfair Display', 'serif'],
        body: ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'display-lg-mobile': ['48px', { lineHeight: '1.1', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.2', fontWeight: '400' }],
        'body-lg': ['20px', { lineHeight: '1.6', letterSpacing: '0.01em', fontWeight: '300' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.15em', fontWeight: '600' }],
      },
      spacing: {
        unit: '8px',
        gutter: '32px',
        'margin-safe': '48px',
        'container-max': '1200px',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
    },
  },
  plugins: [],
};
